/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexeditor;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
       //hexeditor.HexEditor classUnderTest = new HexEditor();
       System.out.println(classUnderTest);
    }
}
